In [2]:
import numpy as np

In [3]:
a = [1,2,3]
np.array(a)

array([1, 2, 3])

In [4]:
l1 = [1.2,'a']
print(type(l1))
a2 = np.array(l1)
print(type(a2))

<class 'list'>
<class 'numpy.ndarray'>


# dtype을 변경해보자

In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #float64bit 자주씀
print(array_float, array_float.dtype)

#array float > array int
array_float_2 = np.array([1.1,2.2,3.3])
array_int_2 = array_float_2.astype('int32')
print(array_int_2, array_int_2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


# arange, zeros, ones

In [ ]:
# 기준 셀 위에 추가 :: a
# 기준 셀 아래에 추가 :: b
# 선택된 셀 지우기 :: x
# 실수로 선택된 셀을 지움 :: z

In [8]:
for i in range(3):
    print(i)

0
1
2


In [9]:
# np.arange
sq_array = np.arange(10)
print(sq_array)
print(sq_array.dtype, sq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [11]:
# zeros 함수
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [14]:
# reshape
array1 = sq_array.reshape(2,5)
array2 = array1.reshape(-1,1)
array3 = array2.reshape(-1,2)

print(array1)
print(array2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
# 3차원 ndarray
array4 = np.arange(8)
array3d = array4.reshape((2,2,2))
print('array3d\n', array3d.tolist())

# 3차원 ndarray > 2차원 ndarray
array3d.reshape(-1,1)

array3d
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

# ndarray dataset indexing
* numpy 에서의 ndarray 내에서 특정 데이터 혹은 일부를 선택

In [ ]:
#### 1. 특정 data 추출
#### 2. slicing
#### 3. fancy indexing
#### 4. boolean indexing

In [26]:
# 1~9까지의 데이터 생성
array1 = np.arange(start=1,stop=10)

# index [0]부터 시작
array1
value=array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [29]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [30]:
# 2차원에 해당하는 인덱싱 :: 슬라이싱 추출
array1d
array1d_1 = array1d[:3]
print(array1d_1)
print(array1d[3:])
print(array1d[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
answer1 = array2d[0:2,0] # 슬라이싱을 활용한 인덱싱
print('array2d[0:2,0]->',answer1.tolist())

answer2 = array2d[[0,1],0] # 특정값 추출을 활용한 인덱싱
print('array2d[[0,1],0]->',answer2.tolist())

## 2차원 형태로 인덱싱
answer3 = array2d[[0,1], 0:1] # 특정값 추출을 활용한 인덱싱
print('array2d[[0,1],0:1]->',answer3.tolist())

array2d[[0,1]]

array2d[0:2,0]-> [1, 4]
array2d[[0,1],0]-> [1, 4]
array2d[[0,1],0:1]-> [[1], [4]]


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# array1d[array1d>5]와의 비교
boolean_index = np.array([False, False, False, False,False,True,True,True,True])
array1d[boolean_index]

array([6, 7, 8, 9])

### sort()와 argsort() 함수

In [35]:
# list에 해당하는 sort()
a = [1,4,2,3]
print(a.sort())
print(a)
a # 원본이 변환되어 있음..

None


In [ ]:
# ## 출력값이 없는 함수의 사례
# def add(x,y):
# #     print("%d, %d의 합은 %d입니다" % (x,y, x+y))
#     return x+y
# result = add(x=3,y=5)
# print(result)

summary :: 원본을 변환시키는 함수는
           return값이 없으므로
           출력값이 없는 겁니다.

           만약 원본을 유지시키는 함수라면
           return값을 받을 것이므로
           출력값이 있게 됩니다.

In [38]:
org_array = np.array([3,1,9,5])
print('원본 행렬:\n', org_array)

# np.sort()를 통해 정렬
sorted_array1 = np.sort(org_array)
print('np.sort() 적용 후 원본 행렬:\n', org_array)
print('np.sort() 적용 후 정렬 행렬:\n', sorted_array1)

# ndarray.sort()를 통해 정렬
sorted_array2 = org_array.sort()


원본 행렬:
 [3 1 9 5]
np.sort() 적용 후 원본 행렬:
 [3 1 9 5]
np.sort() 적용 후 정렬 행렬:
 [1 3 5 9]
