01 Scikit-learn 소개와 특징

사이킷런은 파이선 머신러닝 라이브러리 중 가장 많이 사용됨

In [28]:
import sklearn
print(sklearn.__version__)

1.0.2


<붓꽃 품종 분류> - p.38

In [29]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score as acc_sc

In [30]:
iris = load_iris()
iris_data = iris.data # whole X data
#type(iris)

In [31]:
print("iris의 키 : \n", iris.keys())

iris의 키 : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [32]:
print(iris['DESCR'][:193]+'\n')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre



In [33]:
print("타겟의 이름:", iris['target_names'])

타겟의 이름: ['setosa' 'versicolor' 'virginica']


In [34]:
print("특성의 이름 : \n", iris['feature_names'])

특성의 이름 : 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
print("data의 타입:", type(iris['data']))

data의 타입: <class 'numpy.ndarray'>


In [36]:
print("data의 크기:", iris['data'].shape)

data의 크기: (150, 4)


In [37]:
print("data의 처음 다섯 행:\n", iris['data'][:5])

data의 처음 다섯 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [38]:
iris_target = iris.target # y값들 .. whole y_data
print('iris target값 : ', iris_target)
print('iris target명 : ', iris.target_names)

iris target값 :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 :  ['setosa' 'versicolor' 'virginica']


In [41]:
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)
iris_df.head()
iris['y_lable'] = iris_target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
from sklearn.model_selection import train_test_split # 학습데이터와 테스트데이터 융합

In [50]:
# train_test_split 사용예제
test_array = np.arange(1,11)
test_array2 = np.arange(101,111)
train_test_split(test_array, test_array2, test_size=0.2, random_state=156)

[array([ 9,  1,  2, 10,  4,  8,  6,  3]),
 array([7, 5]),
 array([109, 101, 102, 110, 104, 108, 106, 103]),
 array([107, 105])]

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(iris_data, iris_target, test_size=0.2, random_state=11)

In [58]:
print(X_train.shape)
print(X_test.shape) # --> 값 예측
print(Y_train.shape)
print(Y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [59]:
# 의사결정나무 객체화
df_clf = DecisionTreeClassifier(random_state=11)

In [60]:
df_clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=11)

In [63]:
# 학습된 알고리즘을 통해 예측 수행
pred_df = df_clf.predict(X_test)

In [64]:
print('예측정확도 : {0}'.format(acc_sc(Y_test, pred_df)))

예측정확도 : 0.9333333333333333


# overfitting and underfitting

* overfitting : 과대적합; 각 데이터에 대한 정확도는 좋은데, 에러 발생
* underfitting : 과소적합; 지나친 단순화로 인한 에러 발생

## 03. train_test_split을 하지 않는다면?

In [67]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score as acc_sc

import pandas as pd
import numpy as np

In [68]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
X_train = iris.data # X값 전체
y_train = iris.target # y값 전체

In [69]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [70]:
dt_clf.predict(X_train)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [71]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [72]:
y_train == dt_clf.predict(X_train)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [73]:
acc_sc(y_train, dt_clf.predict(X_train))

1.0

정확도 100%? 이상하다!

그래서, 결국에 train과 test를 분리하여야 한다... -> 홀드아웃(hold_out)