In [4]:
# 1~9까지의 데이터 생성 ndarray
import numpy as np

In [5]:
# 특정데이터 연습
sq_array = np.arange(1,10)
sq_array[6]

7

In [9]:
# 슬라이싱
print(sq_array[:3])
print(sq_array[3:])
print(sq_array[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [16]:
# 2차원 데이터에서의 fancy indexing
print('sq_array의 차원은:{0}'.format(sq_array.ndim))
print('sq_array의 형태는:{0}'.format(sq_array.shape))

sq_array2d = sq_array.reshape(3,3)
print('\n',sq_array2d)

sq_array의 차원은:1
sq_array의 형태는:(9,)

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
## 2차원에서의 특정값 추출
# print('row=1, col=0 index의 값은: {0}'.format(sq_array2d[1,0]))
# print('row=1, col=2 index의 값은: {0}'.format(sq_array2d[1,2]))

## 2차원에서의 슬라이싱
# print('\narray2d:\n',sq_array2d[0:2,0:2])
# print('\narray2d:\n',sq_array2d[0:2,1])
# print('\narray2d:\n',sq_array2d[0:2,1:2])

## 2차원에서의 팬시 인덱싱(fancy indexing)
# 이중 리스트의 형태로 이루어진 인덱싱

# print('원본 행렬:\n',sq_array2d)
# print('array2d[[0,1],2]=>',sq_array2d[[0,1],2],'\n') # 출력된 형태가 1차원
# print('array2d[[0,1],2]=>\n',sq_array2d[[0,1],2:],'\n') # 출력된 형태가 2차원

## boolean indexing
array1d = np.arange(start=1,stop=10)
#[]안에 boolean indexing을 적용
print(array1d[array1d>5])
array1d[np.array([False, False, False, False, False,  True,  True,  True,  True])]

[6 7 8 9]


array([6, 7, 8, 9])

### 행렬의 정렬 - sort()와 argsort()

In [43]:
org_array=[6,8,2,4]
print('원본 행렬:', org_array)

#np.sort()로 정렬
sorted_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 원본:', org_array) # 원본은 안바뀜
print('np.sort()호출 후 정렬된 행렬:', sorted_array1) # 새로운 변수로 정의됨

#array.sort()로 정렬
sorted_array2 = org_array.sort()
print('array.sort()호출 후 반환된 원본:', org_array) # 원본이 바뀜
print('array.sort()호출 후 정렬된 행렬:', sorted_array2) # 새로운 변수는 None

원본 행렬: [6, 8, 2, 4]
np.sort()호출 후 반환된 원본: [6, 8, 2, 4]
np.sort()호출 후 정렬된 행렬: [2 4 6 8]
array.sort()호출 후 반환된 원본: [2, 4, 6, 8]
array.sort()호출 후 정렬된 행렬: None


In [46]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬:',sort)

array([8, 6, 4, 2])

In [7]:
array2d = np.array([[8,12],
                    [7,11]])
print('row방향 정렬' )
sorted_array=np.sort(array2d, axis=0)

row방향 정렬


In [5]:
# arg_sort()함수 :: 정렬된 행렬의 인덱스 반환!
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) # 1,3,5,9 == R에서의 order함수와 같다
print(type(sort_indices))
print('오름차순 정렬된 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
오름차순 정렬된 행렬의 인덱스: [1 0 3 2]


In [6]:
# 내림차순을 원할때
org_array = np.array([3,1,9,5])
sort_indices1 = np.argsort(org_array)[::-1]
print(type(sort_indices1))
print('내림차순 정렬된 행렬의 인덱스:',sort_indices1)

<class 'numpy.ndarray'>
내림차순 정렬된 행렬의 인덱스: [2 3 0 1]


In [8]:
# 행렬의 내적을 위한 함수 dot
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

print('A의 shape:', A.shape)
print('B의 shape:', B.shape)

A의 shape: (2, 3)
B의 shape: (3, 2)
